### ISSUE TITLE
Add SSSOM sssupport

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/koza#108]
Let's do our mapping with Koza.

We need to leave the original mapping support code available, since it's 

**Config changes:**
- [ ] Add config option for list of SSSOM mapping files
- [ ] Add config option for ordered list of preferred prefixes

**SSSOM reader:**
- [ ] Add a SSSOM reader to bring the files and load them into memory (probably using SSSOM-py?). It probably could be filtered on load to only hang on to rows that include the preferred ID prefixes

**SSSOM utils:**
- [ ] If SSSOM-py doesn't already do this, add a function that takes the preferred ID list and brings returns the mapped ID

**kgx writer:**
- [ ] If SSSOM is configured for the ingest, add original_subject/original_object fields to the header
- [ ] use the sssom utils to populate subject, object, original_subject, original_object

Note: I had been thinking of writing both un-mapped output and separately write the mapped files, but that feels like kind of a waste of space, since you can (fairly) easily rewind the mapping logic

**Comment by matentzn** [comment]
sssupport. 

🐍 

Is this about rewiring at ingest time?

**Comment by kevinschaper** [comment]
@matentzn yeah, I wasn't sure if it should happen in koza, kgx, or a standalone tool and I got excited about koza support because we don't need to iterate over all the rows a second time.  

(Plus also that ideally koza and kgx should probably both be able to rewire based on a sssom file/df)

**Comment by matentzn** [comment]
OK cool. So the rewire code will leave in a single module that is shared by both tools, or will this be duplicated? I would be interested to review that code once it is there, just so you know if you would like another pair of eyes on it!

**Comment by kevinschaper** [comment]
Is that for applying mappings to rewire edges or transforming the SSSOM itself into other formats?

**Comment by glass-ships** [comment]
see #109
