### ISSUE TITLE
Current `sssom` pin does not install versions compatible with recent oaklib

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/koza#118]
Noticed with KG-Phenio: https://github.com/Knowledge-Graph-Hub/kg-phenio/issues/126
koza wants sssom "^0.3.41":
https://github.com/monarch-initiative/koza/blob/ba0ba45192dd23a0c8ed7bc8876856ce9c4ddbb8/pyproject.toml#L27C18-L27C18
Could we relax this and allow 0.4 and above?
Older versions have incompatibilities with more recent oaklib releases (or perhaps just the most recent ones, like v0.5.24)

**Comment by glass-ships** [comment]
thanks harry, yeah we should. this is a minor annoyance i have with poetry, actually. it treats carets differently for zero vs. non-zero version numbers. 

I'll make a PR relaxing this shortly

**Comment by caufieldjh** [comment]
thanks @glass-ships !

**Comment by glass-ships** [comment]
ok, koza v0.5.3 should work for you! feel free to re-open this issue if you still run into trouble
