### ISSUE TITLE
Improve validation messages

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/koza#14]
Right now it's a stack trace, and a default pydantic validation message. In the Xenbase branch I'm adding a step to print the last row processed above the stack trace - but we should do better, the data that doesn't match should ideally fit in the same terminal screen as the validation error, and if we can provide helpful text along with the regex that needs to be met, that would also be nice.

This pydantic issue might be a good starting place for tracking down how to customize validation messages: https://github.com/samuelcolvin/pydantic/issues/177

**Comment by putmantime** [comment]
This may be a Biolink Model - Pydantic issue.
That code may end up inside of LinkML.

Still unclear where this should be addressed

**Comment by kevinschaper** [comment]
I don't think we're likely to circle back to this. The combination of the pydantic message with the knowledge that the row is printed above the stack trace has been good enough. 

It's possible that there will be changes to make in LinkML pydanticgen when the next major version of Pydantic is released, but I don't think we're going to do anything in Koza.
