### ISSUE TITLE
Remove collector layer, go straight to writer

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/koza#21]
With the biolink conversion being the responsibility of the writer, this layer isn't doing anything, and as Kent noted in #20, it's more clear in the individual ingest scripts to call write than collect

**Comment by kshefchek** [comment]
we may opt to keep that function but just rename it from collect to write, and then if some more complexity pops up we'll still have a nice proxy function called write (that's maybe a yagni violation)
