### ISSUE TITLE
Add a tutorial for using Koza from python rather than command line

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/koza#33]
aka, a friendly doc for using Koza from a kg-hub

* Link to config reference
* How to execute from python
* Where to get translation table?

**Comment by caufieldjh** [comment]
I would find this very helpful!

**Comment by kevinschaper** [comment]
@caufieldjh I think this might be the main thing you need: 

```
from koza.cli_runner import transform_source

transform_source("./examples/string/protein-links-detailed.yaml",
                 "output", "tsv", "./examples/translation_table.yaml", None)
```

**Comment by kevinschaper** [comment]
I added the small example above to the docs as a part of #44
