### ISSUE TITLE
Add tsv output option in addition to kgx

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/koza#38]
Currently the tsv output format will give you kgx, but longer term we should support both simple tsv outputs and the kgx format. Perhaps we could couple with this ticket adding in simple streaming to std out in cases where no file name is passed to koza and jsonl or tsv are selected as the output format.

**Comment by putmantime** [comment]
This could expand Koza's use to write to other schemas like SSSOM

**Comment by sagehrke** [comment]
Will wait to do this until we have a use case. @kevinschaper
