### ISSUE TITLE
Add line number limit to CLI to quickly test sources

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/koza#51]
In dipper we had a [command line option](https://github.com/monarch-initiative/dipper/blob/master/dipper-etl.py#L73) to limit the number of lines processed.  This is useful for quickly evaluating an ingest while developing as an alternative to using a debugger.

**Comment by glass-ships** [comment]
`row_limit` paramater added to `transform()` method, passed down to CSV, JSON, and JSONL Readers. Limits processing to specified number of rows per source file (ie. if you pull from 2 source files and set row_limit to 3, final edges file will have 6 entries) . 

Still need to implement JSON and JSONL tests

**Comment by glass-ships** [comment]
Commit 9436f1cfd293115102e4c51d817b83f20ca3f6c8 adds unit tests for JSON and JSONL Readers with `row_limit` params included. Ideally, an integration test would be written to verify the entire chain, maybe by parameterizing [the existing test_row_limit](tests/integration/test_row_limit.py), but at least for now we can confirm that the `row_limit` parameter works properly in the readers. 

MR #73 should be ready for inspection.
